stages:
  - test
  - deploy
  - announce

test:
  image: node:12.13
  services:
    - mongo:latest
  script:
    - npm install
    - npm test
  only:
    - master

deploy:
  image: ruby:2.5.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
  only:
    - master

announce:
    stage: announce
    script:
        - curl --data chat_id=$TELEGRAM_CHAT_ID --data-urlencode text="[$CI_PROJECT_NAME - $CI_COMMIT_REF_NAME] $CI_COMMIT_TITLE by $GITLAB_USER_NAME" $TELEGRAM_BOT_URL/sendMessage